CREATE TABLE househld (
PRIMARY KEY (HHX)
);

CREATE TABLE familyxx (
PRIMARY KEY (FMX, HHX),
FOREIGN KEY (HHX) REFERENCES househld(HHX)
);

CREATE TABLE personsx (
PRIMARY KEY (FPX, FMX, HHX),
FOREIGN KEY (FMX) REFERENCES familyxx(FMX),
FOREIGN KEY (HHX) REFERENCES househld(HHX)
);

CREATE TABLE injpoiep (
PRIMARY KEY (IPEPNO, FMX, HHX, FPX),
FOREIGN KEY (FMX) REFERENCES familyxx(FMX),
FOREIGN KEY (HHX) REFERENCES househld(HHX),
FOREIGN KEY (FPX) REFERENCES personsx(FPX)
);


CREATE TABLE samadult (
PRIMARY KEY (FPX, FMX, HHX),
FOREIGN KEY (FMX) REFERENCES familyxx(FMX),
FOREIGN KEY (HHX) REFERENCES househld(HHX)
);

CREATE TABLE samchild (
PRIMARY KEY (FPX, FMX, HHX),
FOREIGN KEY (FMX) REFERENCES familyxx(FMX),
FOREIGN KEY (HHX) REFERENCES househld(HHX)
)
